name: Allure Report

env:
    SOLUTION_FILE: FreeAdCopyAutomation.sln
    BUILD_CONFIGURATION: Debug

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
    autotests:
        name: Run tests and generate Allure Report
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@main
  
            - name: Set up .NET
              uses: actions/setup-dotnet@main
              with:
                dotnet-version: |
                    9.0.x

            - name: Restore NuGet packages
              run: dotnet restore --packages .packages ${{ env.SOLUTION_FILE }}

            - name: Build solution
              run: dotnet build --no-restore --configuration ${{ env.BUILD_CONFIGURATION }} ${{ env.SOLUTION_FILE }}

            - name: Test solution
              run: dotnet test --no-build --configuration ${{ env.BUILD_CONFIGURATION }} ${{ env.SOLUTION_FILE }}
              continue-on-error: true

            - name: Get Allure history
              uses: actions/checkout@v4
              if: always()
              continue-on-error: true
              with:
                ref: gh-pages
                path: gh-pages

            - name: Generate Allure Report
              uses: simple-elf/allure-report-action@v1.7
              if: always()
              with:
                allure_results: allure-results
                allure_history: allure-history

            - name: Deploy report to GitHub Pages
              if: always()
              uses: peaceiris/actions-gh-pages@v3
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: allure-history
                publish_branch: gh-pages
                
            - name: Post a message in a channel
              uses: slackapi/slack-github-action@v2.0.0
              with:
                webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
                webhook-type: incoming-webhook
                payload: |
                  text: "*GitHub Action build result*: ${{ job.status }}\n${{  github.event.head_commit.url }}\nSee Detailed Report at: https://sajidmanzoor.github.io/FreeAdCopyAutomation-Selenium"          