name: Allure Report

env:
    SOLUTION_FILE: FreeAdCopyAutomation.sln
    BUILD_CONFIGURATION: Debug

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
    autotests:
        name: Run tests and generate Allure Report
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@main
  
            - name: Set up .NET
              uses: actions/setup-dotnet@main
              with:
                dotnet-version: |
                    9.0.x

            - name: Restore NuGet packages
              run: dotnet restore --packages .packages ${{ env.SOLUTION_FILE }}

            - name: Build solution
              run: dotnet build --no-restore --configuration ${{ env.BUILD_CONFIGURATION }} ${{ env.SOLUTION_FILE }}

            - name: Test solution
              run: dotnet test --no-build --configuration ${{ env.BUILD_CONFIGURATION }} ${{ env.SOLUTION_FILE }}
              continue-on-error: true

            - name: Get Allure history
              uses: actions/checkout@v4
              if: always()
              continue-on-error: true
              with:
                ref: gh-pages
                path: gh-pages
                
            - name: Generate Allure Report
              uses: simple-elf/allure-report-action@master
              if: always()
              with:
                allure_results: bin/Debug/net9.0/allure-results
                allure_history: allure-history

            - name: Deploy report to GitHub Pages
              if: always()
              uses: peaceiris/actions-gh-pages@main
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: allure-results
                publish_branch: gh-pages

            - name: Slack Notification
              uses: rtCamp/action-slack-notify@v2
              if: always()
              env:
                SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
                SLACK_USERNAME: sajid
                SLACK_TITLE: "Environment: Staging \n Build Status: ${{ job.status }}"
                SLACK_COLOR: ${{ job.status }}
                SLACK_MESSAGE: "GitHub Action build result: ${{ job.status }}\n${{ github.event.head_commit.url }}\nSee Detailed Report at: https://sajidmanzoor.github.io/FreeAdCopyAutomation-Selenium"
                      